### PR TITLE
Metrics

### PR DESCRIPTION
**Pull request by TristanGomez44**
Reduce feature dim and batch nb in debug mode to reduce computation.
Can load ResNet or Densenet
Require to pass annotation folder as arg
Filter original data to keep only data from the same class as synthetic data

### CODE REVIEW

**Comment by maxime915** [comment]
Here are my opinions, to be discussed with you and Maxence.

- The code is too complex for a single file : classes and reusable functions should be exported and usable from other scripts. The core of main should be rewritten in a dedicated function and the script should only use argparse and call this function.
- This should be in a module of the nsw_da_mediacal_image package (imports should thus be relative only)
- docstrings would be really nice (even ChatGPT generated ones)
- provide sensible default for parameters (assuming the code is run in the Docker container)
- argument parser could use the format with default values (see what is done in the refactor-main branch)
- use of `os.path.exists` and `os.mkdirs` could be replaced by pathlib for better coherence
- ~redefinition of `vector_list` at https://github.com/multitel-ai/nsw-da-medical-image/blob/4bca0fd9051c6ea2c14cfab617d7030df93674fc/img_generator_metrics.py#L342 which is never written to before being stored into a tensor https://github.com/multitel-ai/nsw-da-medical-image/blob/4bca0fd9051c6ea2c14cfab617d7030df93674fc/img_generator_metrics.py#L359 does this not result in an empty tensor ?~ My bad, they are used in the hook. Does the `vector_list = []` shadows the variable in the hook as well ? unsure...
- OrigImageFolder and SynthImageFolder differ only from how they load the files, the rest of their behavior is exactly the same. Consider using a single class that stores only img_list, dataset_label, transform, labels
- What was the reason for not using NSWDataset ?

**Comment by TristanGomez44** [comment]
I have checked the id of vector list during the computation. Indeed, when it is reset to an empty list at the beginning of the loop, its id changes. However, vector_list keeps getting filled by the pytorch hook so this is not a problem.
Also, I did not use NSWDataset because I need to filter out images that do not belong to the label of the synthetic data.

**Comment by maxime915** [comment]
Awesome ! I took the liberty to change the imports from absolute to relative inside the package, and to copy the doctstring from the function to the parser as well. I'll be running this a bit before final approval :wink:

**Comment by TristanGomez44** [comment]
Nice thank you !

**Comment by maxime915** [comment]
Here are a few nitpicks after my first coffee : 

- The README.md indicates that the key for the focal plane is "focal-plane" yet the code uses "focal_plane". See https://github.com/multitel-ai/nsw-da-medical-image/blob/afa7b06b638ca27e4ef55cf66cb9e2cd6bef6fac/README.md?plain=1#L97. What do we agree on as the key ?
- `ImageFile.LOAD_TRUNCATED_IMAGES = True` need not be in both the script and the module. I think the module is the right place to put this, but I'm open to alternatives.
- Having a variable to list all phases and take the index breaks encapsulation. IMO, all instances of `all_labels_list.index(...)` should be replaced by `enums.Phase(...).idx()` and the variable `all_labels_list` should be removed.

Aside from that, all is good !

**Comment by TristanGomez44** [comment]
I think we should use "focal-plane" as indicated in the readme so I made the corresponding modification.
I agree with all the modifications you suggested.

**Pull request merged**
